import type { Pedido, Producto, PuntoEntrega, Sede } from './types'
import {
  BODEGA_DEFAULT,
  MOTIVO_VENTA_DEFAULT,
  contactoEntregaVacio,
  contactoRetiraVacio,
  despachoVacio,
} from './types'

/** Usuario mock de la sesión actual (prototipo sin auth real). */
export const clienteActualMock = {
  clienteId: 'c1',
  clienteNombre: 'Constructora Restrepo',
  usuarioNombre: 'María Restrepo',
  email: 'mrestrepo@restrepo.co',
  /** Plazo de pago del maestro del cliente: lo heredan sus pedidos nuevos. */
  plazoCodigo: '30D',
}

export const productosMock: Producto[] = [
  // --- Cemento en saco ---
  {
    id: 'p1',
    codigo: 'COD-0042',
    nombre: 'Cemento Gris Estructural',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 50 kg',
    unidad: 'Bulto 50kg',
    precio: 32500,
    iva: 0.19,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p2',
    codigo: 'COD-0043',
    nombre: 'Cemento Uso General',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 28900,
    iva: 0.19,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p3',
    codigo: 'COD-0051',
    nombre: 'Cemento Blanco Premium',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 50 kg',
    unidad: 'Bulto 50kg',
    precio: 45200,
    iva: 0.19,
    imagen: '/images/saco-blanco.png',
  },
  {
    id: 'p4',
    codigo: 'COD-0067',
    nombre: 'Cemento Estructural Tipo ART',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 42.5 kg',
    unidad: 'Bulto 42.5kg',
    precio: 21500,
    iva: 0.19,
    imagen: '/images/saco-mortero.png',
  },
  // --- Línea de acabados (saco) ---
  {
    id: 'p7',
    codigo: 'COD-0201',
    nombre: 'Pegante para Porcelanato',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 38900,
    iva: 0.19,
    imagen: '/images/saco-pegante.png',
  },
  {
    id: 'p8',
    codigo: 'COD-0202',
    nombre: 'Estuco interior',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 26400,
    iva: 0.19,
    imagen: '/images/saco-estuco.png',
  },
  {
    id: 'p12',
    codigo: 'COD-0205',
    nombre: 'Pegante cerámico',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 24900,
    iva: 0.19,
    imagen: '/images/saco-pegante-ceramico.png',
  },
  
  {
    id: 'p11',
    codigo: 'COD-0204',
    nombre: 'Estuco relleno interior',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 24900,
    iva: 0.19,
    imagen: '/images/saco-estuco-relleno.png',
  },
  {
    id: 'p9',
    codigo: 'COD-0203',
    nombre: 'Boquilla para Juntas',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 5 kg',
    unidad: 'Bulto 5kg',
    precio: 14900,
    iva: 0.19,
    imagen: '/images/saco-boquilla.png',
  },
  {
    id: 'p13',
    codigo: 'COD-0206',
    nombre: 'Estuco relleno exterior',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 24900,
    iva: 0.19,
    imagen: '/images/saco-estuco-relleno-exterior.png',
  },
  
  // --- Cemento a granel ---
  {
    id: 'p10',
    codigo: 'COD-0110',
    nombre: 'Cemento a Granel ART',
    marca: 'San Marcos',
    tipo: 'granel',
    categoria: 'cemento',
    presentacion: 'Tonelada (granel)',
    unidad: 'Ton',
    precio: 698000,
    iva: 0.19,
    imagen: '/images/granel.png',
  },
]
/** Sucursales/plantas de despacho de la compañía (catálogo fijo). */
export const sedesMock: Sede[] = [
  {
    id: 'sd1',
    nombre: 'Cali – Planta SC',
    ciudad: 'Cali',
    direccion: 'Km 24 Vía Panorama Cali – Buga',
    activa: true,
  },
  {
    id: 'sd2',
    nombre: 'Yumbo – San Marcos',
    ciudad: 'Yumbo',
    direccion: 'Corregimiento San Marcos, Yumbo',
    activa: true,
  },
  {
    id: 'sd3',
    nombre: 'Palmira – Zona Franca',
    ciudad: 'Palmira',
    direccion: 'Zona Franca Palmira, Bodega 12',
    activa: true,
  },
]

/** Puntos de entrega/retiro del cliente, cada uno asignado a una sede de despacho. */
export const puntosEntregaMock: PuntoEntrega[] = [
  {
    id: 's1',
    nombre: 'Obra Torre Central',
    tipo: 'obra',
    direccion: 'Cra 45 # 26-85',
    ciudad: 'Bogotá',
    sedeDespachoId: 'sd1',
    contactoNombre: 'Ing. Marcela Ríos',
    contactoTelefono: '3104567890',
  },
  {
    id: 's2',
    nombre: 'Punto de Venta Norte',
    tipo: 'punto_venta',
    direccion: 'Calle 170 # 8-32',
    ciudad: 'Bogotá',
    sedeDespachoId: 'sd1',
    contactoNombre: 'Carlos Méndez',
    contactoTelefono: '3201234567',
  },
  {
    id: 's3',
    nombre: 'Obra Conjunto Las Palmas',
    tipo: 'obra',
    direccion: 'Av. Las Palmas km 12',
    ciudad: 'Medellín',
    sedeDespachoId: 'sd2',
    contactoNombre: 'Ing. Julián Vélez',
    contactoTelefono: '3009876543',
  },
  {
    id: 's4',
    nombre: 'Punto de Venta Sur',
    tipo: 'punto_venta',
    direccion: 'Cra 50 # 8 Sur-12',
    ciudad: 'Cali',
    sedeDespachoId: 'sd3',
    contactoNombre: 'Andrea Lozano',
    contactoTelefono: '3157654321',
  },
]

/** Asesor de Servicio mock: firma las acciones de Gestión en la bitácora. */
export const asesorServicioMock = {
  nombre: 'Paola Cifuentes',
  email: 'pcifuentes@sanmarcos.co',
}

/**
 * Pedidos semilla del store central: cubren los tres estados, varios clientes,
 * mezcla de estadoCredito, puntos de entrega y creadores (estilo pantalla real
 * de Ventas). El consecutivo definitivo no lleva prefijo; los borradores usan T_.
 */
export const pedidosMock: Pedido[] = [
  {
    id: 'ped1',
    numero: '269488',
    estado: 'aprobado',
    pvc: 'PVC-275190',
    estadoCredito: 'aprobado',
    formaPago: 'Crédito',
    plazoCodigo: '30D',
    clienteId: 'c1',
    clienteNombre: 'Constructora Restrepo',
    fechaCreacion: '2026-06-28T09:15:00.000Z',
    fechaSolicitud: '2026-06-28T10:02:00.000Z',
    creadorEmail: 'mrestrepo@restrepo.co',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: 'entregar',
    despacho: {
      sedeId: 'sd1',
      puntoEntregaId: 's1',
      ordenCompra: 'OC-4410',
      necesitaEstiba: true,
      necesitaDescarga: true,
      observaciones: '',
    },
    contactoEntrega: {
      nombreRecibe: 'Marcela Ríos',
      celular: '3104567890',
      correo: 'mrios@restrepo.co',
    },
    contactoRetira: contactoRetiraVacio(),
    items: [
      { id: 'it1', productoId: 'p1', cantidad: 200, fechaEntrega: '2026-07-03' },
      { id: 'it2', productoId: 'p2', cantidad: 80, fechaEntrega: '2026-07-03' },
    ],
    sedeFacturaId: 'sd1',
    bodegaCodigo: BODEGA_DEFAULT,
    motivoVenta: MOTIVO_VENTA_DEFAULT,
    bitacora: [
      {
        id: 'bt1',
        fecha: '2026-06-28T09:18:00.000Z',
        accion: 'comentario_documento',
        usuario: 'mrestrepo@restrepo.co',
        detalle:
          'CODIGO: T_301502 TOTAL: 0.00 CONSTRUCTORA RESTREPO - OBRA TORRE CENTRAL - ING. MARCELA RIOS - 3104567890 --Nombre: MARCELA RIOS --Telefono: 3104567890 --Correo: mrios@restrepo.co',
        adjuntos: [],
      },
      {
        id: 'bt2',
        fecha: '2026-06-28T10:02:00.000Z',
        accion: 'documento_solicitado',
        usuario: 'mrestrepo@restrepo.co',
        detalle:
          'CODIGO: 269488 TOTAL: 10486280.00 CONSTRUCTORA RESTREPO - OBRA TORRE CENTRAL - ING. MARCELA RIOS - 3104567890 --Nombre: MARCELA RIOS --Telefono: 3104567890 --Correo: mrios@restrepo.co',
        adjuntos: ['orden-compra-OC-4410.pdf'],
      },
      {
        id: 'bt3',
        fecha: '2026-06-28T13:40:00.000Z',
        accion: 'documento_aprobado',
        usuario: 'Paola Cifuentes',
        detalle: 'CODIGO: 269488 TOTAL: 10486280.00',
        adjuntos: [],
      },
      {
        id: 'bt4',
        fecha: '2026-06-28T13:42:00.000Z',
        accion: 'documento_mensaje',
        usuario: 'Paola Cifuentes',
        detalle:
          'Se ha enviado mensaje al pedido PVC-275190 por el estado Aprobado con el siguiente contenido CSM: Hemos recibido tu solicitud y queda radicado con PVC-275190 Destino Bogotá - CONSTRUCTORA RESTREPO Cantidad 280 Bultos.',
        adjuntos: [],
      },
    ],
  },
  {
    id: 'ped3',
    numero: '269512',
    estado: 'solicitado',
    pvc: null,
    estadoCredito: 'aprobado',
    formaPago: 'Crédito',
    plazoCodigo: '60D',
    clienteId: 'c1',
    clienteNombre: 'Constructora Restrepo',
    fechaCreacion: '2026-07-08T11:05:00.000Z',
    fechaSolicitud: '2026-07-08T11:40:00.000Z',
    creadorEmail: 'jvelez@restrepo.co',
    moneda: 'COP',
    tipoProducto: 'granel',
    metodoDespacho: 'entregar',
    despacho: {
      sedeId: 'sd2',
      puntoEntregaId: 's3',
      ordenCompra: 'OC-4472',
      necesitaEstiba: false,
      necesitaDescarga: false,
      observaciones: 'Coordinar ingreso de tractomula',
    },
    contactoEntrega: {
      nombreRecibe: 'Julián Vélez',
      celular: '3009876543',
      correo: 'jvelez@restrepo.co',
    },
    contactoRetira: contactoRetiraVacio(),
    items: [{ id: 'it3', productoId: 'p10', cantidad: 34, fechaEntrega: '2026-07-18' }],
    sedeFacturaId: null,
    // Granel de cemento ART: sale de la bodega SCART, no de la default.
    bodegaCodigo: 'SCART',
    motivoVenta: MOTIVO_VENTA_DEFAULT,
    bitacora: [
      {
        id: 'bt5',
        fecha: '2026-07-08T11:08:00.000Z',
        accion: 'comentario_documento',
        usuario: 'jvelez@restrepo.co',
        detalle:
          'CODIGO: T_301618 TOTAL: 0.00 CONSTRUCTORA RESTREPO - OBRA CONJUNTO LAS PALMAS - ING. JULIAN VELEZ - 3009876543 --Nombre: JULIAN VELEZ --Telefono: 3009876543 --Correo: jvelez@restrepo.co',
        adjuntos: [],
      },
      {
        id: 'bt6',
        fecha: '2026-07-08T11:40:00.000Z',
        accion: 'documento_solicitado',
        usuario: 'jvelez@restrepo.co',
        detalle:
          'CODIGO: 269512 TOTAL: 28241080.00 CONSTRUCTORA RESTREPO - OBRA CONJUNTO LAS PALMAS - ING. JULIAN VELEZ - 3009876543 --Nombre: JULIAN VELEZ --Telefono: 3009876543 --Correo: jvelez@restrepo.co',
        adjuntos: [],
      },
    ],
  },
  {
    id: 'ped4',
    numero: '269531',
    estado: 'solicitado',
    pvc: null,
    estadoCredito: 'sin_aprobar',
    formaPago: 'Crédito',
    plazoCodigo: '30D',
    clienteId: 'c3',
    clienteNombre: 'Obras Civiles del Valle',
    fechaCreacion: '2026-07-10T16:20:00.000Z',
    fechaSolicitud: '2026-07-10T17:05:00.000Z',
    creadorEmail: 'alozano@ocvalle.com',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: 'entregar',
    despacho: {
      sedeId: 'sd3',
      puntoEntregaId: 's4',
      ordenCompra: 'OC-1207',
      necesitaEstiba: true,
      necesitaDescarga: false,
      observaciones: '',
    },
    contactoEntrega: {
      nombreRecibe: 'Andrea Lozano',
      celular: '3157654321',
      correo: 'alozano@ocvalle.com',
    },
    contactoRetira: contactoRetiraVacio(),
    items: [
      { id: 'it4', productoId: 'p8', cantidad: 45, fechaEntrega: '2026-07-20' },
      { id: 'it5', productoId: 'p9', cantidad: 30, fechaEntrega: '2026-07-20' },
    ],
    sedeFacturaId: null,
    bodegaCodigo: BODEGA_DEFAULT,
    motivoVenta: MOTIVO_VENTA_DEFAULT,
    bitacora: [
      {
        id: 'bt7',
        fecha: '2026-07-10T16:24:00.000Z',
        accion: 'comentario_documento',
        usuario: 'alozano@ocvalle.com',
        detalle:
          'CODIGO: T_301655 TOTAL: 0.00 OBRAS CIVILES DEL VALLE - PUNTO DE VENTA SUR - ANDREA LOZANO - 3157654321 --Nombre: ANDREA LOZANO --Telefono: 3157654321 --Correo: alozano@ocvalle.com',
        adjuntos: [],
      },
      {
        id: 'bt8',
        fecha: '2026-07-10T17:05:00.000Z',
        accion: 'documento_solicitado',
        usuario: 'alozano@ocvalle.com',
        detalle:
          'CODIGO: 269531 TOTAL: 1945650.00 OBRAS CIVILES DEL VALLE - PUNTO DE VENTA SUR - ANDREA LOZANO - 3157654321 --Nombre: ANDREA LOZANO --Telefono: 3157654321 --Correo: alozano@ocvalle.com',
        adjuntos: [],
      },
    ],
  },
  {
    // Reproduce la fila 269554 de la pantalla real: badge "Aprobado" con
    // texto de crédito "Sin Aprobar" (ver TODO de EstadoCredito en types).
    id: 'ped2',
    numero: '269554',
    estado: 'aprobado',
    pvc: 'PVC-275251',
    estadoCredito: 'sin_aprobar',
    formaPago: 'Contado',
    plazoCodigo: 'CC',
    clienteId: 'c2',
    clienteNombre: 'Ferretería El Cóndor',
    fechaCreacion: '2026-07-11T14:40:00.000Z',
    fechaSolicitud: '2026-07-11T15:12:00.000Z',
    creadorEmail: 'compras@elcondor.com',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: 'retira',
    despacho: {
      sedeId: 'sd1',
      puntoEntregaId: 's2',
      ordenCompra: 'OC-8821',
      necesitaEstiba: false,
      necesitaDescarga: false,
      observaciones: 'Retira en la mañana',
    },
    contactoEntrega: contactoEntregaVacio(),
    contactoRetira: {
      nombreConductor: 'Pedro Salazar',
      cedula: '79456123',
      placa: 'XKD421',
      celular: '3159871234',
    },
    items: [{ id: 'it6', productoId: 'p7', cantidad: 60, fechaEntrega: '2026-07-06' }],
    sedeFacturaId: 'sd2',
    // Saco despachado desde la bodega externa de Pereira.
    bodegaCodigo: 'BEPER',
    motivoVenta: MOTIVO_VENTA_DEFAULT,
    bitacora: [
      {
        id: 'bt9',
        fecha: '2026-07-11T14:43:00.000Z',
        accion: 'comentario_documento',
        usuario: 'compras@elcondor.com',
        detalle:
          'CODIGO: T_301688 TOTAL: 0.00 FERRETERIA EL CONDOR - PUNTO DE VENTA NORTE - CARLOS MENDEZ - 3201234567 --Nombre: PEDRO SALAZAR --Telefono: 3159871234',
        adjuntos: [],
      },
      {
        id: 'bt10',
        fecha: '2026-07-11T15:12:00.000Z',
        accion: 'documento_solicitado',
        usuario: 'compras@elcondor.com',
        detalle:
          'CODIGO: 269554 TOTAL: 2777460.00 FERRETERIA EL CONDOR - PUNTO DE VENTA NORTE - CARLOS MENDEZ - 3201234567 --Nombre: PEDRO SALAZAR --Telefono: 3159871234',
        adjuntos: ['cedula-conductor.pdf', 'tarjeta-propiedad-XKD421.pdf'],
      },
      {
        id: 'bt11',
        fecha: '2026-07-11T16:05:00.000Z',
        accion: 'documento_aprobado',
        usuario: 'Paola Cifuentes',
        detalle: 'CODIGO: 269554 TOTAL: 2777460.00',
        adjuntos: [],
      },
      {
        id: 'bt12',
        fecha: '2026-07-11T16:07:00.000Z',
        accion: 'documento_mensaje',
        usuario: 'Paola Cifuentes',
        detalle:
          'Se ha enviado mensaje al pedido PVC-275251 por el estado Aprobado con el siguiente contenido CSM: Hemos recibido tu solicitud y queda radicado con PVC-275251 Destino Bogotá - FERRETERIA EL CONDOR Cantidad 60 Bultos.',
        adjuntos: [],
      },
    ],
  },
  {
    id: 'ped5',
    numero: 'T_301740',
    estado: 'en_construccion',
    pvc: null,
    estadoCredito: 'aprobado',
    formaPago: 'Crédito',
    plazoCodigo: '30D',
    clienteId: 'c1',
    clienteNombre: 'Constructora Restrepo',
    fechaCreacion: '2026-07-13T08:30:00.000Z',
    fechaSolicitud: null,
    creadorEmail: 'mrestrepo@restrepo.co',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: null,
    despacho: despachoVacio(),
    contactoEntrega: contactoEntregaVacio(),
    contactoRetira: contactoRetiraVacio(),
    items: [{ id: 'it7', productoId: 'p3', cantidad: 25, fechaEntrega: null }],
    sedeFacturaId: null,
    bodegaCodigo: BODEGA_DEFAULT,
    motivoVenta: MOTIVO_VENTA_DEFAULT,
    bitacora: [
      {
        id: 'bt13',
        fecha: '2026-07-13T08:32:00.000Z',
        accion: 'comentario_documento',
        usuario: 'mrestrepo@restrepo.co',
        detalle:
          'CODIGO: T_301740 TOTAL: 0.00 CONSTRUCTORA RESTREPO - PENDIENTE PUNTO DE ENTREGA --Nombre: --Telefono: --Correo:',
        adjuntos: [],
      },
    ],
  },
  {
    id: 'ped6',
    numero: 'T_301722',
    estado: 'en_construccion',
    pvc: null,
    estadoCredito: 'sin_aprobar',
    formaPago: 'Contado',
    plazoCodigo: 'CC',
    clienteId: 'c2',
    clienteNombre: 'Ferretería El Cóndor',
    fechaCreacion: '2026-07-13T17:55:00.000Z',
    fechaSolicitud: null,
    creadorEmail: 'compras@elcondor.com',
    moneda: 'COP',
    tipoProducto: null,
    metodoDespacho: null,
    despacho: despachoVacio(),
    contactoEntrega: contactoEntregaVacio(),
    contactoRetira: contactoRetiraVacio(),
    items: [],
    sedeFacturaId: null,
    bodegaCodigo: BODEGA_DEFAULT,
    motivoVenta: MOTIVO_VENTA_DEFAULT,
    bitacora: [
      {
        id: 'bt14',
        fecha: '2026-07-13T17:57:00.000Z',
        accion: 'comentario_documento',
        usuario: 'compras@elcondor.com',
        detalle:
          'CODIGO: T_301722 TOTAL: 0.00 FERRETERIA EL CONDOR - PENDIENTE PUNTO DE ENTREGA --Nombre: --Telefono: --Correo:',
        adjuntos: [],
      },
    ],
  },
]
