import type { Pedido, Producto, PuntoEntrega, Sede } from './types'
import { datosEntregaVacios, datosRetiraVacios } from './types'

/** Usuario mock de la sesión actual (prototipo sin auth real). */
export const clienteActualMock = {
  clienteId: 'c1',
  clienteNombre: 'Constructora Restrepo',
  usuarioNombre: 'María Restrepo',
  email: 'mrestrepo@restrepo.co',
}

export const productosMock: Producto[] = [
  // --- Cemento en saco ---
  {
    id: 'p1',
    codigo: 'COD-0042',
    nombre: 'Cemento Gris Estructural',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 50 kg',
    unidad: 'Bulto 50kg',
    precio: 32500,
    iva: 0.19,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p2',
    codigo: 'COD-0043',
    nombre: 'Cemento Uso General',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 28900,
    iva: 0.19,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p3',
    codigo: 'COD-0051',
    nombre: 'Cemento Blanco Premium',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 50 kg',
    unidad: 'Bulto 50kg',
    precio: 45200,
    iva: 0.19,
    imagen: '/images/saco-blanco.png',
  },
  {
    id: 'p4',
    codigo: 'COD-0067',
    nombre: 'Cemento Estructural Tipo ART',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'cemento',
    presentacion: 'Saco 42.5 kg',
    unidad: 'Bulto 42.5kg',
    precio: 21500,
    iva: 0.19,
    imagen: '/images/saco-mortero.png',
  },
  // --- Línea de acabados (saco) ---
  {
    id: 'p7',
    codigo: 'COD-0201',
    nombre: 'Pegante para Porcelanato',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 38900,
    iva: 0.19,
    imagen: '/images/saco-pegante.png',
  },
  {
    id: 'p8',
    codigo: 'COD-0202',
    nombre: 'Estuco interior',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 26400,
    iva: 0.19,
    imagen: '/images/saco-estuco.png',
  },
  {
    id: 'p12',
    codigo: 'COD-0205',
    nombre: 'Pegante cerámico',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 24900,
    iva: 0.19,
    imagen: '/images/saco-pegante-ceramico.png',
  },
  
  {
    id: 'p11',
    codigo: 'COD-0204',
    nombre: 'Estuco relleno interior',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 24900,
    iva: 0.19,
    imagen: '/images/saco-estuco-relleno.png',
  },
  {
    id: 'p9',
    codigo: 'COD-0203',
    nombre: 'Boquilla para Juntas',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 5 kg',
    unidad: 'Bulto 5kg',
    precio: 14900,
    iva: 0.19,
    imagen: '/images/saco-boquilla.png',
  },
  {
    id: 'p13',
    codigo: 'COD-0206',
    nombre: 'Estuco relleno exterior',
    marca: 'San Marcos',
    tipo: 'saco',
    categoria: 'linea_acabados',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 24900,
    iva: 0.19,
    imagen: '/images/saco-estuco-relleno-exterior.png',
  },
  
  // --- Cemento a granel ---
  {
    id: 'p10',
    codigo: 'COD-0110',
    nombre: 'Cemento a Granel ART',
    marca: 'San Marcos',
    tipo: 'granel',
    categoria: 'cemento',
    presentacion: 'Tonelada (granel)',
    unidad: 'Ton',
    precio: 698000,
    iva: 0.19,
    imagen: '/images/granel.png',
  },
]
/** Sucursales/plantas de despacho de la compañía (catálogo fijo). */
export const sedesMock: Sede[] = [
  {
    id: 'sd1',
    nombre: 'Cali – Planta SC',
    ciudad: 'Cali',
    direccion: 'Km 24 Vía Panorama Cali – Buga',
    activa: true,
  },
  {
    id: 'sd2',
    nombre: 'Yumbo – San Marcos',
    ciudad: 'Yumbo',
    direccion: 'Corregimiento San Marcos, Yumbo',
    activa: true,
  },
  {
    id: 'sd3',
    nombre: 'Palmira – Zona Franca',
    ciudad: 'Palmira',
    direccion: 'Zona Franca Palmira, Bodega 12',
    activa: true,
  },
]

/** Puntos de entrega/retiro del cliente, cada uno asignado a una sede de despacho. */
export const puntosEntregaMock: PuntoEntrega[] = [
  {
    id: 's1',
    nombre: 'Obra Torre Central',
    tipo: 'obra',
    direccion: 'Cra 45 # 26-85',
    ciudad: 'Bogotá',
    sedeDespachoId: 'sd1',
    contactoNombre: 'Ing. Marcela Ríos',
    contactoTelefono: '3104567890',
  },
  {
    id: 's2',
    nombre: 'Punto de Venta Norte',
    tipo: 'punto_venta',
    direccion: 'Calle 170 # 8-32',
    ciudad: 'Bogotá',
    sedeDespachoId: 'sd1',
    contactoNombre: 'Carlos Méndez',
    contactoTelefono: '3201234567',
  },
  {
    id: 's3',
    nombre: 'Obra Conjunto Las Palmas',
    tipo: 'obra',
    direccion: 'Av. Las Palmas km 12',
    ciudad: 'Medellín',
    sedeDespachoId: 'sd2',
    contactoNombre: 'Ing. Julián Vélez',
    contactoTelefono: '3009876543',
  },
  {
    id: 's4',
    nombre: 'Punto de Venta Sur',
    tipo: 'punto_venta',
    direccion: 'Cra 50 # 8 Sur-12',
    ciudad: 'Cali',
    sedeDespachoId: 'sd3',
    contactoNombre: 'Andrea Lozano',
    contactoTelefono: '3157654321',
  },
]

/**
 * Pedidos semilla del store central: cubren los tres estados, varios clientes,
 * mezcla de estadoCredito, puntos de entrega y creadores (estilo pantalla real
 * de Ventas). El consecutivo definitivo no lleva prefijo; los borradores usan T_.
 */
export const pedidosMock: Pedido[] = [
  {
    id: 'ped1',
    numero: '269488',
    estado: 'aprobado',
    pvc: 'PVC-275190',
    estadoCredito: 'aprobado',
    formaPago: 'Crédito',
    plazoCredito: 'Crédito 30 días',
    clienteId: 'c1',
    clienteNombre: 'Constructora Restrepo',
    fechaCreacion: '2026-06-28T09:15:00.000Z',
    fechaSolicitud: '2026-06-28T10:02:00.000Z',
    creadorEmail: 'mrestrepo@restrepo.co',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: 'entregar',
    datosEntrega: {
      sedeDespachoId: 'sd1',
      puntoEntregaId: 's1',
      ordenCompra: 'OC-4410',
      nombreRecibe: 'Marcela Ríos',
      celular: '3104567890',
      correo: 'mrios@restrepo.co',
      necesitaEstiba: true,
      necesitaDescarga: true,
      observaciones: '',
    },
    datosRetira: datosRetiraVacios(),
    items: [
      { productoId: 'p1', cantidad: 200, fechaEntrega: '2026-07-03' },
      { productoId: 'p2', cantidad: 80, fechaEntrega: '2026-07-03' },
    ],
  },
  {
    id: 'ped3',
    numero: '269512',
    estado: 'solicitado',
    pvc: null,
    estadoCredito: 'aprobado',
    formaPago: 'Crédito',
    plazoCredito: 'Crédito 60 días',
    clienteId: 'c1',
    clienteNombre: 'Constructora Restrepo',
    fechaCreacion: '2026-07-08T11:05:00.000Z',
    fechaSolicitud: '2026-07-08T11:40:00.000Z',
    creadorEmail: 'jvelez@restrepo.co',
    moneda: 'COP',
    tipoProducto: 'granel',
    metodoDespacho: 'entregar',
    datosEntrega: {
      sedeDespachoId: 'sd2',
      puntoEntregaId: 's3',
      ordenCompra: 'OC-4472',
      nombreRecibe: 'Julián Vélez',
      celular: '3009876543',
      correo: 'jvelez@restrepo.co',
      necesitaEstiba: false,
      necesitaDescarga: false,
      observaciones: 'Coordinar ingreso de tractomula',
    },
    datosRetira: datosRetiraVacios(),
    items: [{ productoId: 'p10', cantidad: 34, fechaEntrega: '2026-07-18' }],
  },
  {
    id: 'ped4',
    numero: '269531',
    estado: 'solicitado',
    pvc: null,
    estadoCredito: 'sin_aprobar',
    formaPago: 'Crédito',
    plazoCredito: 'Crédito 30 días',
    clienteId: 'c3',
    clienteNombre: 'Obras Civiles del Valle',
    fechaCreacion: '2026-07-10T16:20:00.000Z',
    fechaSolicitud: '2026-07-10T17:05:00.000Z',
    creadorEmail: 'alozano@ocvalle.com',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: 'entregar',
    datosEntrega: {
      sedeDespachoId: 'sd3',
      puntoEntregaId: 's4',
      ordenCompra: 'OC-1207',
      nombreRecibe: 'Andrea Lozano',
      celular: '3157654321',
      correo: 'alozano@ocvalle.com',
      necesitaEstiba: true,
      necesitaDescarga: false,
      observaciones: '',
    },
    datosRetira: datosRetiraVacios(),
    items: [
      { productoId: 'p8', cantidad: 45, fechaEntrega: '2026-07-20' },
      { productoId: 'p9', cantidad: 30, fechaEntrega: '2026-07-20' },
    ],
  },
  {
    // Reproduce la fila 269554 de la pantalla real: badge "Aprobado" con
    // texto de crédito "Sin Aprobar" (ver TODO de EstadoCredito en types).
    id: 'ped2',
    numero: '269554',
    estado: 'aprobado',
    pvc: 'PVC-275251',
    estadoCredito: 'sin_aprobar',
    formaPago: 'Contado',
    plazoCredito: 'Contado',
    clienteId: 'c2',
    clienteNombre: 'Ferretería El Cóndor',
    fechaCreacion: '2026-07-11T14:40:00.000Z',
    fechaSolicitud: '2026-07-11T15:12:00.000Z',
    creadorEmail: 'compras@elcondor.com',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: 'retira',
    datosEntrega: datosEntregaVacios(),
    datosRetira: {
      sedeDespachoId: 'sd1',
      puntoEntregaId: 's2',
      ordenCompra: 'OC-8821',
      nombreConductor: 'Pedro Salazar',
      cedula: '79456123',
      placa: 'XKD421',
      celular: '3159871234',
      necesitaEstiba: false,
      observaciones: 'Retira en la mañana',
    },
    items: [{ productoId: 'p7', cantidad: 60, fechaEntrega: '2026-07-06' }],
  },
  {
    id: 'ped5',
    numero: 'T_301740',
    estado: 'en_construccion',
    pvc: null,
    estadoCredito: 'aprobado',
    formaPago: 'Crédito',
    plazoCredito: 'Crédito 30 días',
    clienteId: 'c1',
    clienteNombre: 'Constructora Restrepo',
    fechaCreacion: '2026-07-13T08:30:00.000Z',
    fechaSolicitud: null,
    creadorEmail: 'mrestrepo@restrepo.co',
    moneda: 'COP',
    tipoProducto: 'saco',
    metodoDespacho: null,
    datosEntrega: datosEntregaVacios(),
    datosRetira: datosRetiraVacios(),
    items: [{ productoId: 'p3', cantidad: 25, fechaEntrega: null }],
  },
  {
    id: 'ped6',
    numero: 'T_301722',
    estado: 'en_construccion',
    pvc: null,
    estadoCredito: 'sin_aprobar',
    formaPago: 'Contado',
    plazoCredito: 'Contado',
    clienteId: 'c2',
    clienteNombre: 'Ferretería El Cóndor',
    fechaCreacion: '2026-07-13T17:55:00.000Z',
    fechaSolicitud: null,
    creadorEmail: 'compras@elcondor.com',
    moneda: 'COP',
    tipoProducto: null,
    metodoDespacho: null,
    datosEntrega: datosEntregaVacios(),
    datosRetira: datosRetiraVacios(),
    items: [],
  },
]
